# Generated by Django 2.2 on 2019-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mNO', models.CharField(max_length=32)),
                ('mMark', models.CharField(max_length=256)),
                ('mPrice', models.CharField(max_length=32)),
                ('mNote', models.CharField(max_length=1024)),
                ('mFile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=70)),
                ('temp', models.CharField(max_length=32)),
            ],
        ),
    ]
